src/objects/Addon__c.object
<CustomObject>
    <label>Addon</label>
    <nameField>
        <label>Addon Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addons</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/BookedFlight__c.object
<CustomObject>
    <fields>
        <fullName>DateFrom__c</fullName>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateTo__c</fullName>
        <label>Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Booked Flights</relationshipLabel>
        <relationshipName>Booked_Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Booked Flight</label>
    <nameField>
        <label>Booked Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booked Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flight__c.object
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Price__c.object
<CustomObject>
    <fields>
        <fullName>Addon__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Addon</label>
        <referenceTo>Addon__c</referenceTo>
        <relationshipLabel>Prices</relationshipLabel>
        <relationshipName>Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>DateFrom__c</fullName>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateTo__c</fullName>
        <label>Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Prices</relationshipLabel>
        <relationshipName>Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Price</label>
    <nameField>
        <label>Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BookingController.cls
public class BookingController {
    public BookedFlight__c searchFlight { get; set; }
    public List<Price__c> filtrFlight { get; set; }
    public String dataJSON { get; set; }
    public String flightValue;
    public String addonValue;
    public String dateFromValue;
    public String dateToValue;
    
    public BookingController() {
        this.searchFlight = new BookedFlight__c();
        this.flightValue = '';
        this.addonValue = '';
        this.dateFromValue = '';
        this.dateToValue = '';
        this.dataJSON = '';
    }
 
    public void searchFlights() {
        flightValue = ApexPages.currentPage().getParameters().get('flight');
        addonValue = ApexPages.currentPage().getParameters().get('addon');
        dateFromValue = ApexPages.currentPage().getParameters().get('dateFrom');
        dateToValue = ApexPages.currentPage().getParameters().get('dateTo');

        ApexPages.getMessages().clear();
        
        if (Date.valueOf(dateFromValue) > Date.valueOf(dateToValue)) {
            ApexPages.addMessage(
                new ApexPages.Message(
                    ApexPages.Severity.ERROR, 
                    'Date From can not be greater than Date To'
                )
            );
            return;
        }
      
        if (flightValue.equals('') && addonValue.equals('') || dateFromValue.equals('') || dateToValue.equals('')) {
            ApexPages.addMessage(
                new ApexPages.Message(
                    ApexPages.Severity.ERROR, 
                    'Fields can not be empty'
                )
            );
            return;
        }

        List<String> condition = new List<String>();
        
        String flightName = flightValue;
        String addonName = addonValue;
        Date dateFrom = Date.valueOf(dateFromValue);
        Date dateTo = Date.valueOf(dateToValue);

        if (flightName != null && addonName == null) {
            condition.add('Flight__r.Name = :flightName');
        } else if (flightName == null && addonName != null) {
            condition.add('Addon__r.Name = :addonName');
        } else if (flightName != null && addonName != null) {
            condition.add('Flight__r.Name = :flightName AND Addon__r.Name = :addonName');
        }
        
        String query = 'SELECT Value__c, Flight__c, Addon__c, DateFrom__c, DateTo__c ' + 
            ' FROM Price__c ' + 
            ' WHERE ' + String.join(condition, ' AND ') + 
            ' AND DateFrom__c <= :dateFrom ' +
            ' AND DateTo__c >= :dateTo ' + 
            ' ORDER BY Value__c ASC ' +
            ' LIMIT 1000';
        
        List<Price__c> prices = (List<Price__c>)Database.query(query);
        dataJSON = JSON.serialize(prices);
        /*filtrFlight = prices;*/
    }
    
    public void bookFlight() {
        flightValue = ApexPages.currentPage().getParameters().get('flight');
        addonValue = ApexPages.currentPage().getParameters().get('addon');
        dateFromValue = ApexPages.currentPage().getParameters().get('dateFrom');
        dateToValue = ApexPages.currentPage().getParameters().get('dateTo');
        
        ApexPages.getMessages().clear();
        
        if (Date.valueOf(dateFromValue) > Date.valueOf(dateToValue)) {
            ApexPages.addMessage(
                new ApexPages.Message(
                    ApexPages.Severity.ERROR, 
                    'Date From can not be greater than Date To'
                )
            );
            return;
        }
      
        if (flightValue.equals('') && addonValue.equals('') || dateFromValue.equals('') || dateToValue.equals('')) {
            ApexPages.addMessage(
                new ApexPages.Message(
                    ApexPages.Severity.ERROR, 
                    'Fields can not be empty'
                )
            );
            return;
        }
        
        List<String> condition = new List<String>();
        
        String flightName = flightValue;
        String addonName = addonValue;
        Date dateFrom = Date.valueOf(dateFromValue);
        Date dateTo = Date.valueOf(dateToValue);

        if (flightName != null && addonName == null) {
            condition.add('Flight__r.Name = :flightName');
        } else if (flightName == null && addonName != null) {
            condition.add('Addon__r.Name = :addonName');
        } else if (flightName != null && addonName != null) {
            condition.add('Flight__r.Name = :flightName AND Addon__r.Name = :addonName');
        }
        
        String query = 'SELECT Value__c, Flight__c, Addon__c, DateFrom__c, DateTo__c ' + 
            ' FROM Price__c ' + 
            ' WHERE ' + String.join(condition, ' AND ') + 
            ' AND DateFrom__c <= :dateFrom ' +
            ' AND DateTo__c >= :dateTo ' + 
            ' ORDER BY Value__c ASC ' +
            ' LIMIT 1000';
        
        List<Price__c> prices = (List<Price__c>)Database.query(query);
        
        Price__c flightPrice = new Price__c();
        Price__c addonPrice = new Price__c();
        
        for (Price__c price : prices) {
            if (price.Flight__c != null) {
                flightPrice = price;
            }
            if (price.Addon__c != null) {
                addonPrice = price;
            }
        }
        
        Decimal flightAmount = 0.0;
        Decimal addonAmount = 0.0;
        Integer allocation = dateFrom.daysBetween(dateTo) + 1;
        if (flightPrice.Id != null) {
            flightAmount = flightPrice.Value__c * allocation;
        } 
        if (addonPrice.Id != null) {
            addonAmount = addonPrice.Value__c * allocation;
        }
        
        insert new BookedFlight__c(
            Flight__c = this.searchFlight.Flight__c,
            Addon__c = this.searchFlight.Addon__c,
            DateFrom__c = this.searchFlight.DateFrom__c,
            DateTo__c = this.searchFlight.DateTo__c,
            TotalPrice__c = flightAmount +  addonAmount
        );
    }
    
}