src/objects/BookedFlight__c.object
<CustomObject>
    <fields>
        <fullName>DateFrom__c</fullName>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateTo__c</fullName>
        <label>Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Booked Flights</relationshipLabel>
        <relationshipName>Booked_Flights</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Booked Flight</label>
    <nameField>
        <label>Booked Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Booked Flights</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Flight__c.object
<CustomObject>
    <label>Flight</label>
    <nameField>
        <label>Flight Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flights</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Price__c.object
<CustomObject>
    <fields>
        <fullName>DateFrom__c</fullName>
        <label>Date From</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>DateTo__c</fullName>
        <label>Date To</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Flight__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Flight</label>
        <referenceTo>Flight__c</referenceTo>
        <relationshipLabel>Prices</relationshipLabel>
        <relationshipName>Prices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Price</label>
    <nameField>
        <label>Price Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BookFlightHandler.cls
@RestResource(urlMapping='/book_flight')
global with sharing class BookFlightHandler  {

    @HttpPost
    global static String create() {
        RestRequest request = RestContext.request;
        RestResponse response = RestContext.response;
        Map<String, Object> params = new Map<String, Object>();
        Map<String, Object> result = new Map<String, Object>();
        BookedFlight__c bookedFlight = new BookedFlight__c();

        try {
            params = (Map<String, Object>) JSON.deserializeUntyped(request.requestBody.toString());
        } catch(JSONException ex) {
            result.put('message', 'Flight does not booked' + ex.getMessage() + ' ' + ex.getStackTraceString());
            result.put('status', 'failed');
        }

        //get params
        Date dateFrom = Date.valueOf(params.get('date_from').toString());
        Date dateTo = Date.valueOf(params.get('date_to').toString());
        List<Price__c> availablePrices = [
            SELECT Flight__r.Name, Value__c
            FROM Price__c
            WHERE DateFrom__c <= :dateFrom AND DateTo__c >= :dateTo
            LIMIT 100
        ];

        if ( !availablePrices.isEmpty() ) {
            Decimal totalPrice = dateFrom.daysBetween(dateTo)*availablePrices[0].Value__c;
            insert new BookedFlight__c (
                Flight__c = availablePrices[0].Flight__c,
                DateFrom__c = dateFrom,
                DateTo__c = dateTo,
                TotalPrice__c = totalPrice
                );

            result.put('message', 'Flight successfully booked');
            result.put('status', 'booked');
            result.put('price', totalPrice);

        } else {
            result.put('message', 'This flights are busy');
            result.put('status', 'booked');
        }

        return JSON.serialize(result);

    }

}